Fix error with python 3.9
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
getchildren() has been removed in python 3.9

Signed-off-by: Etienne Champetier <echampetier@anevia.com>